Review 1
n1belung63/cpp-peer-review pull request #3
Opened 2023-11-18 11:07 UTC by n1belung63

2023-11-22 16:54 UTC, Jetrac requested changes
1, 3 задание - круто, но второе я бы переделал

2023-11-23 07:45 UTC, n1belung63 commented on task_3.cpp
> +    const DBQuery query = [&person_pars, &db] {
Поправил.

2023-11-23 07:51 UTC, n1belung63 commented on task_3.cpp
> +    const int MAX_MONTH = 12;
Да, тут я допустил ошибку

2023-11-23 09:26 UTC, n1belung63 commented on task_3.cpp
> +    }
Красиво сделать пользовательский класс ошибки наследник от domain error не получилось - поскольку он отвечает только за выбрасывание исключений, а проверку на валидность надо держать отдельно, и он выглядит уже излишним. Поэтому просто вынес проверки в отдельную функцию

2023-11-23 13:09 UTC, Jetrac approved these changes
https://youtu.be/LabIat9t-uY?si=37aOY-JsB73pj9sf

2023-11-23 13:19 UTC, merged